# Generated by Django 6.0.2 on 2026-02-14 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Default Title', max_length=207)),
                ('message', models.TextField(default='')),
                ('type', models.CharField(choices=[('request_received', 'Request Received'), ('request_accepted', 'Request Accepted'), ('request_declined', 'Request Declined'), ('review_completed', 'Review Completed')], default='request_received', max_length=50)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
