# Generated by Django 6.0.2 on 2026-02-14 04:57

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
        ('review_requests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('photos', 'Photos'), ('bio', 'Bio'), ('prompts', 'Prompts')], max_length=20)),
                ('score', models.FloatField(validators=[django.core.validators.MinValueValidator(0.5), django.core.validators.MaxValueValidator(5.0)])),
                ('liked', models.TextField()),
                ('disliked', models.TextField()),
                ('suggestions', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quick_impression', models.BooleanField(blank=True, null=True)),
                ('overall_score', models.FloatField(blank=True, null=True)),
                ('additional_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profileversion')),
                ('review_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='review_requests.reviewrequest')),
            ],
        ),
    ]
