# Generated by Django 6.0.2 on 2026-02-14 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProfilePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='profile_photos/')),
                ('order', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField()),
                ('dating_intent', models.CharField(choices=[('go_with_the_flow', 'Go with the flow'), ('casual', 'Casual'), ('serious', 'Serious')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('version_number', models.IntegerField(default=1)),
                ('average_score', models.FloatField(default=0)),
                ('positive_impressions', models.IntegerField(default=0)),
                ('negative_impressions', models.IntegerField(default=0)),
                ('improvement_percentage', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
                ('is_custom', models.BooleanField(default=False)),
            ],
        ),
    ]
