# Generated by Django 6.0.2 on 2026-02-14 04:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profileversion',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='profiles.profile'),
        ),
        migrations.AddField(
            model_name='profilephoto',
            name='profile_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='profiles.profileversion'),
        ),
        migrations.AddField(
            model_name='prompt',
            name='profile_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prompts', to='profiles.profileversion'),
        ),
    ]
